name: Recreate Dev Branch

on: delete

jobs:
  recreateBranch:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch' && github.event.ref == 'dev'
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
          
      - name: Recreate Dev Branch
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'dev@taling.me'
          git branch dev
          git push origin dev
